codecov:
  token: c2f0ce36-17ad-4668-bb1b-f1b72dedf3fc
  comment:
    after_n_builds: 9

coverage:
  precision: 2
  round: down
  range: "90...100"
  status:
    project:
      default:
        target: auto
        threshold: 2.0%
        informational: true
